name = "orison"
main = "src/index.js"
compatibility_date = "2024-02-01"
routes = [
  { pattern = "brake.run" },
  { pattern = "dev.brake.run" }
]

[[kv_namespaces]]
binding = "PUZZLES"
id = "b973caae74e74b2fb2f603c0d4bbbea5"

[dev]
port = 5002
local_protocol = "http"

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true
